export const DATA_SOURCE = 'DATA_SOURCE';

export const USER = 'USER';
export const USER_PROFILE = 'USER_PROFILE';
export const USER_SESSION = 'USER_SESSION';
export const USER_OTP = 'USER_OTP';
export const USER_DOCUMENT = 'USER_DOCUMENT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const EMAIL_VERIFY_TOKEN = 'EMAIL_VERIFY_TOKEN';
export const REPORT = 'REPORT';

export const ADMIN_USER = 'ADMIN_USER_REPOSITORY';
export const ADMIN_USER_SESSION = 'ADMIN_USER_SESSION_REPOSITORY';
export const ROLE = 'ROLE_REPOSITORY';
export const ROLE_ACCESS = 'ROLE_ACCESS_REPOSITORY';

export const PLACE_TYPE = 'PLACE_TYPE';
export const ROOM_TYPE = 'ROOM_TYPE';
export const AMENITIES = 'AMENITIES';
export const SHARED_SPACES = 'SHARED_SPACES';
export const HOUSE_RULES = 'HOUSE_RULES';
export const SAFETY_AMENITIES = 'SAFETY_AMENITIES';

export const PROPERTIES = 'PROPERTIES';
export const PROPERTY_AMENITIES = 'PROPERTY_AMENITIES';
export const PROPERTY_BATHROOMS = 'PROPERTY_BATHROOMS';
export const PROPERTY_SAFETY_AMENITIES = 'PROPERTY_SAFETY_AMENITIES';
export const PROPERTY_SPACES = 'PROPERTY_SPACES';
export const PROPERTY_HOUSERULES = 'PROPERTY_HOUSERULES';
export const PROPERTY_IMAGES = 'PROPERTY_IMAGES';
export const PROPERTY_STEP2 = 'PROPERTY_STEP2';
export const PROPERTY_STEP3 = 'PROPERTY_STEP3';
export const PROPERTY_STATUS = 'PROPERTY_STATUS';
export const PROPERTY_DATES = 'PROPERTY_DATES';
export const PROPERTY_VIEWS = 'PROPERTY_VIEWS';

export const EXPERIENCE_CATEGORY = 'EXPERIENCE_CATEGORY';
export const EXPERIENCE_SUB_CATEGORY = 'EXPERIENCE_SUB_CATEGORY';
export const EXPERIENCE_LISTING = 'EXPERIENCE_LISTING';
export const EXPERIENCE_STATUS = 'EXPERIENCE_STATUS';
export const EXPERIENCE_STEP_1 = 'EXPERIENCE_STEP_1';
export const EXPERIENCE_STEP_2 = 'EXPERIENCE_STEP_2';
export const EXPERIENCE_STEP_3 = 'EXPERIENCE_STEP_3';
export const EXPERIENCE_STEP_4 = 'EXPERIENCE_STEP_4';
export const EXPERIENCE_STEP_5 = 'EXPERIENCE_STEP_5';
export const EXPERIENCE_SOCIAL_LINKS = 'EXPERIENCE_SOCIAL_LINKS';
export const EXPERIENCE_IMAGES = 'EXPERIENCE_IMAGES';
export const EXPERIENCE_DATES = 'EXPERIENCE_DATES';
export const EXPERIENCE_RULE = 'EXPERIENCE_RULE';
export const EXPERIENCE_LISTING_RULE = 'EXPERIENCE_LISTING_RULE';
export const EXPERIENCE_DAY = 'EXPERIENCE_DAY';
export const EXPERIENCE_STORE_DAY = 'EXPERIENCE_STORE_DAY';
export const EXPERIENCE_DAY_SLOT = 'EXPERIENCE_DAY_SLOT';
export const EXPERIENCE_STORE_DAY_SLOT = 'EXPERIENCE_STORE_DAY_SLOT';
export const EXPERIENCE_ACTIVITIES = 'EXPERIENCE_ACTIVITIES';
export const EXPERIENCE_FEATURES = 'EXPERIENCE_FEATURES';
export const EXPERIENCE_OLD_BOOKING = "EXPERIENCE_OLD_BOOKING";
export const EXPERIENCE_BOOKING_HOST_PROPOSAL = "EXPERIENCE_BOOKING_HOST_PROPOSAL";
export const EXPERIENCE_BOOKING = 'EXPERIENCE_BOOKING';
export const EXPERIENCE_PAYMENT_HISTORY = 'EXPERIENCE_PAYMENT_HISTORY';

export const EXPERIENCE_SPECIAL_DAY = 'EXPERIENCE_SPECIAL_DAY';
export const EXPERIENCE_STORE_SPECIAL_DAY = 'EXPERIENCE_STORE_SPECIAL_DAY';
export const EXPERIENCE_SPECIAL_DAY_SLOT = 'EXPERIENCE_SPECIAL_DAY_SLOT';
export const EXPERIENCE_STORE_SPECIAL_DAY_SLOT = 'EXPERIENCE_STORE_SPECIAL_DAY_SLOT';

export const EXPERIENCE_BULK_DATES = "EXPERIENCE_BULK_DATES";
export const EXPERIENCE_BULK_DATES_SLOTS_ENTITY = "EXPERIENCE_BULK_DATES_SLOTS_ENTITY";
export const EXPERIENCE_SPECIFIC_DATES = "EXPERIENCE_SPECIFIC_DATES";
export const EXPERIENCE_SPECIFIC_DATES_SLOTS_ENTITY = "EXPERIENCE_SPECIFIC_DATES_SLOTS_ENTITY";

export const EXPERIENCE_PUBLIC = "EXPERIENCE_PUBLIC";
export const EXPERIENCE_PRIVATE = "EXPERIENCE_PRIVATE";

export const BOOKINGS = 'BOOKINGS';
export const PAYMENT_HISTORY = 'PAYMENT_HISTORY';

export const CURRENCY_RATES = 'CURRENCY_RATES';
export const CURRENCY = 'CURRENCY';

export const INBOX = 'INBOX';
export const MESSAGE = 'MESSAGE';

export const CANCELLATION = 'CANCELLATION';
export const REFUND = 'REFUND';
export const PAYOUT = 'PAYOUT';

export const REVIEW = 'REVIEW';

export const POPULAR_LOCATION = 'POPULAR_LOCATION';

export const CMS = 'CMS';
export const STATIC_PAGE = 'STATIC_PAGE';

export const PAYOUT_ACCOUNT = 'PAYOUT_ACCOUNT';
export const PAYOUT_DETAILS = 'PAYOUT_DETAILS';

export const SITE_SETTINGS = 'SITE_SETTINGS';
export const SERVICE_FEE = 'SERVICE_FEE';
export const BECOME_A_HOST = 'BECOME_A_HOST';
export const BANNER = 'BANNER';

export const WISH_LIST = 'WISH_LIST';
export const WISH_LIST_ITEMS = 'WISH_LIST_ITEMS';

export const BADGE = 'BADGE';
export const HOW_IT_WORKS_ENTITY = 'HOW_IT_WORKS_ENTITY';
export const PROMO_SECTION = 'PROMO_SECTION';
export const BENEFITS = 'BENEFITS';
export const AD_BANNER = "AD_BANNER";

export const COUPON_CODE = "COUPON_CODE";
export const COUPON_CODE_USAGE = "COUPON_CODE_USAGE";
export const CREDITS = "CREDITS";

export const CITY = "CITY";
export const CITY_POLYGON = "CITY_POLYGON";

export const HOST = "HOST";
export const HOST_BASIC = "HOST_BASIC";
export const HOST_BANK = "HOST_BANK";
export const HOST_TAX = "HOST_TAX";
export const HOST_DOCUMENT = "HOST_DOCUMENT";
export const HOST_CONTACT = "HOST_CONTACT";

export const HOST_SERVICE_FEE = "HOST_SERVICE_FEE";
export const CATEGORY_SERVICE_FEE = "CATEGORY_SERVICE_FEE";

export const EXPERIENCE_REVIEW = "EXPERIENCE_REVIEW";

export const EXPERIENCE_DESCRIPTION_ITEMS = "EXPERIENCE_DESCRIPTION_ITEMS";

export const EXPERIENCE_REFUND = "EXPERIENCE_REFUND";
export const EXPERIENCE_PAYOUT = "EXPERIENCE_PAYOUT";
export const EXPERIENCE_CANCELLATION = "EXPERIENCE_CANCELLATION";

export const DISPUTE = "DISPUTE";
export const DISPUTES_CHAT = "DISPUTES_CHAT";
export const DISPUTES_CHAT_MEDIA = "DISPUTES_CHAT_MEDIA";

export const EXPERIENCE_SLOT_BOOKINGS = "EXPERIENCE_SLOT_BOOKINGS";

export const USER_LEGAL_CONSENT = "USER_LEGAL_CONSENT";

export const USER_EMAIL_OTP = "USER_EMAIL_OTP";



